events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # Fonction generate-password
        location /function/generate-password/ {
            proxy_pass http://generate-password:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Pour matcher exactement s'il n'y a pas le slash final
        location = /function/generate-password {
            proxy_pass http://generate-password:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Fonction generate-2fa
        location /function/generate-2fa/ {
            proxy_pass http://generate-2fa:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location = /function/generate-2fa {
            proxy_pass http://generate-2fa:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Fonction authenticate-user
        location /function/authenticate-user/ {
            proxy_pass http://authenticate-user:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location = /function/authenticate-user {
            proxy_pass http://authenticate-user:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Route fallback
        location / {
            return 404 "Gateway Nginx: Service Not Found";
        }
    }
}
