apiVersion: v2
name: cofrap
description: >-
  PoC backend serverless COFRAP — MariaDB + 3 fonctions OpenFaaS
  (generate-password, generate-2fa, authenticate-user).
type: application
version: 2026.3.2
appVersion: 2026.1.2
keywords:
  - openfaas
  - serverless
  - mariadb
  - 2fa
  - mspr
home: https://github.com/COFRAP-EPSI-2026/cofrap-backend
sources:
  - https://github.com/COFRAP-EPSI-2026/cofrap-backend
maintainers:
  - name: COFRAP-EPSI-2026
    url: https://github.com/COFRAP-EPSI-2026
