{{- if and .Values.secrets.create .Values.mariadb.enabled }}
{{- include "cofrap.requireSecrets" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cofrap.fullname" . }}-mariadb-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cofrap.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: {{ .Values.secrets.mariadbRootPassword | quote }}
  MARIADB_DATABASE: {{ .Values.mariadb.database | quote }}
  MARIADB_USER: {{ .Values.mariadb.user | quote }}
  MARIADB_PASSWORD: {{ .Values.secrets.mariadbPassword | quote }}
{{- end }}
