{{/*
Secrets consommés par les fonctions OpenFaaS — créés dans le namespace `openfaas-fn`
pour être montés en tmpfs sur `/var/openfaas/secrets/` par OpenFaaS.
*/}}
{{- include "cofrap.requireSecrets" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-password
  namespace: {{ .Values.openfaas.functionNamespace }}
  labels:
    {{- include "cofrap.labels" . | nindent 4 }}
    app.kubernetes.io/component: openfaas-secret
  annotations:
    "helm.sh/resource-policy": keep  # éviter une suppression accidentelle au `helm uninstall`
type: Opaque
stringData:
  mariadb-password: {{ .Values.secrets.mariadbPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: encryption-key
  namespace: {{ .Values.openfaas.functionNamespace }}
  labels:
    {{- include "cofrap.labels" . | nindent 4 }}
    app.kubernetes.io/component: openfaas-secret
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  encryption-key: {{ .Values.secrets.encryptionKey | quote }}
